name: Publish Forge

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install virtual framebuffer (if not available) to allow running GUI on a headless server
      run: command -v Xvfb >/dev/null 2>&1 || { sudo apt update && sudo apt install -y xvfb; }

    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Create m2 settings file
      uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "cardforge-repo",
                "username": "${{ secrets.FTP_USERNAME }}",
                "password": "${{ secrets.FTP_PASSWORD }}"
            }]

    - name: Build/Install/Publish to GitHub Packages Apache Maven
    
      run: |
        export DISPLAY=":1"
        Xvfb :1 -screen 0 800x600x8 &
        mvn -U -B clean -P windows-linux install release:clean release:prepare release:perform -T 1C
      env:
        GITHUB_TOKEN: ${{ github.token }}
